src/vcml/models/arm/gicv2.cpp

ppi_handler should consider which cpu the the PPI belongs to. Else always the same PPI input will be checked regardless of cpu. See also 
https://github.com/aut0/vcml/blob/5ee6e2ca8c1bec827c5db90344560360c8cb8929/src/vcml/models/arm/gicv2.cpp#L896-L910
PPI 0-15 will be cpu0, 16-31 cpu1, ...

fix multicore PPI handling

---

include/vcml/models/arm/gicv2.h

Eventhough the special purpose interrupts are not used by peripherals, the configuration registers such as ICFGR exist for them according to the GICv2 spec and are eventually written by software. This can lead to out-of-bounds memory accesses because m_prev_irq is to small if interrupts >1020 are configured.
I added a define for VCML_ARM_GICv2_NSPCL_IRQ. The other line changes in that section are whitespace adjustements.

Special IRQs not considered in m_prev_irq

---

src/vcml/models/generic/sdcard.cpp

m_status is used by make_r1, therefore it should be updated before make_r1 is called.

Fixed bug in sdcard model. 

---

src/vcml/debugging/gdbarch.cpp

Registers should appear in order of increasing register number (e.g. in 'g' and 'G' packets).

Fix order of or1k registers in rsp communication

---

src/vcml/processor.cpp

If the quantum is not a multiple of clock_cycle, after calling `simulate(num_cycles)` there will be time left in the quantum. This
happens because `num_cycles` is rounded down. During the next iteration of the while loop, `num_cycles` will be set to 0. This leads to a not-increasing time, because `simulate(0)` is called which does not increase `local_time()`. To fix this behaviour, `num_cycles` is rounded up to ensure the full quantum can be used in each while loop iteration.

Fix stuck-in-time bug

---

src/vcml/models/arm/gic400.cpp

To get the CPU number of a PPI, the index of the socket needs to be divided by the number of supported PPIs instead of the number of supported CPUs.

Fix gic400-cpu-index bug

---

src/vcml/common/utils.cpp

The `__cxa__demangle` function gets a pointer to an allocated buffer (`dmbuf`) and the size of allocated memory (`dmbufsz`) as paramters. If the allocated size is not big enough to store the demangled name, more memory is allocated using `realloc`. The allocated size is updated (`dmbufsz`) and the pointer to the allocated memory is returned (`res`). The pointer to the originally allocated memory (`dmbufsz`) might be invalid if new memory is allocated using `realloc`.
[`abi::__cxa_demangle` documentation](https://gcc.gnu.org/onlinedocs/libstdc++/libstdc++-html-USERS-4.3/a01696.html)

Fix usage of invalid pointer

---

src/vcml/models/arm/gic400.cpp

If the interrupt acknowledge procedure has not been finished when a new interrupt is raised at the gic, this interrupt is not signaled to the CPU immediately because of the pending one. Once the pending interrupt is completely acknowledged (by writing to the EOI reg), the other pending interrupt should be signaled to the CPU. This is done by calling update after the acknowledged interrupt has been deactivated.

Fix gic update bug

---

src/vcml/common/systemc.cpp

`sim_running()` is not thread-safe & gets called by the rspserver thread,
e.g. while [handling a continue](https://github.com/janweinstock/vcml/blob/abbc42e89130de385aeec9d1b4c63130261b3ed0/src/vcml/debugging/gdbserver.cpp#L147) from a target gdb session.
The value of `simc->get_status()` could change between the switch
evaluation and the return evaluation in the default branch, and thus
could lead to a wrong return value.
In my case, this resulted in an unexpected/wrong SIGTRAP sent to the
target gdb.
This ensures at least a correct interpretation of the current simulation
status, by only calling `simc->get_status()` once.

Avoid misinterpretation of simulation status

---

src/vcml/core/aio.cpp

When `poll` returns with `EINTR`, it means that the call was interrupted by a signal handler. In this case, poll is restarted instead of exiting the simulation with an error.

Ignore EINTR in aio thread

---

src/vcml/debugging/gdbserver.cpp

We seem to have a deadlock in gdbserver, when a user tries to stop simulation via CTRL-C, while the simulation hits a breakpoint at the same time:
* SystemC thread: encounters a breakpoint and wants to pause the GDB server (has SystemC mtx, wants GDB mtx)
* GDB thread: receives a user stop requests and wants to pause the GDB server (has GDB mtx, wants SystemC mtx)

gdbserver deadlock

---

include/vcml/models/arm/gic400.h
src/vcml/models/arm/gic400.cpp

Implement the security features of the gic400.
The security extension can be enabled/disabled by the `secure` property of the gic (default: `false`).

Add gic400 secure features

---

src/vcml/debugging/gdbarch.cpp

For the `reg_read_all` command, the gdb client expects the order of the reg values to be the same as the order of the reg IDs. The `handle_reg_read_all` function sends the values in the order of the cpuregs vector of the target, which is ordered by the order of the gdbarch feature struct.
To solve this issue, the cpuregs vector is sorted based on the reg IDs.

Sort regs of gdbserver target by regno

---

test/CMakeLists.txt
test/unit/exmon.cpp

The other UBSAN errors are solved by machineware-gmbh/systemc#11.

test: exmon did pointer arithmetic with null ptr

---

.github/workflows/asan.yml
.github/workflows/cmake.yml
.github/workflows/coverage.yml
.github/workflows/lint.yml
.github/workflows/nightly.yml
.github/workflows/windows.yml
CMakeLists.txt
include/vcml/models/serial/backend.h
src/vcml/core/processor.cpp
src/vcml/models/generic/memory.cpp
src/vcml/models/serial/backend_term.cpp
src/vcml/models/serial/backend_tui.cpp
src/vcml/models/usb/drive.cpp
src/vcml/models/usb/keyboard.cpp
src/vcml/protocols/can.cpp
src/vcml/protocols/clk.cpp
src/vcml/protocols/eth.cpp
src/vcml/protocols/gpio.cpp
src/vcml/protocols/i2c.cpp
src/vcml/protocols/pci.cpp
src/vcml/protocols/sd.cpp
src/vcml/protocols/serial.cpp
src/vcml/protocols/spi.cpp
src/vcml/protocols/usb_sockets.cpp
src/vcml/protocols/virtio.cpp

Rework VCML to enable unity building.
Introduce a new CMake option, `VCML_UNITY_BUILD`, that enables/disables unity building. By default it is off, and only enabled in the CI. Currently, there are some issues with MSVC, so windows flows will not use it.
Update the cmake & googletest submodules to raise the minimum CMake version and fix some issues with the version string.
Lastly, replace the soon-to-be-deprecated windows-2019 runner with windows-2025.
Please do a rebase merge, so that the commit history is preserved.

CI: Unity builds & more

---

include/vcml/core/processor.h
include/vcml/core/systemc.h
src/vcml/core/processor.cpp
src/vcml/core/systemc.cpp
src/vcml/debugging/gdbserver.cpp
test/unit/async.cpp

When a suspender wants to suspend a processor that is in async mode, the async threads needs to be stopped before suspension. Otherwise, the processor might fetch its registers (update register properties) on suspend while the ISS is still running in the async thread. This leads to faulty behavior on resume if old register values are written back from properties to the ISS.
This PR adds the possibility to block async threads.
The `block_async` methods returns once the thread is blocked. The `unblock_asnyc` methods unblocks the async thread. Async threads can only be blocked during `sc_progress` and `sc_sync` calls.
This PR increases the complexity of the `async_worker`. Private methods are introduced (`async_blocked` and `async_blocked`) and the `progress` member is turned private to …

sc_async: block async thread on suspend

---

src/vcml/core/processor.cpp

When in async mode and a single cycle is left in the quantum, `sc_progress` needs to be called to allow blocking of the async thread. Otherwise, the simulation is stuck.

processor: allow blocking when single cycle left

---

src/vcml/debugging/vspserver.cpp

When the VSP server is launched before the elaboration phase is over, it can happen that a VSP client can suspend the simulation during the elaboration phase. When the client then continues the simulation, the simulation just finishes the elaboration phase because it is automatically suspended afterward.
To prevent this issue, the thread that runs the server is started after the elaboration phase has been finished and the simulation has been suspended.

vspserver: finish elaboration before listening

---

src/vcml/models/arm/gic400.cpp

According the to [ARM's GICv2 spec](https://developer.arm.com/documentation/ihi0048/latest/), for SPIs, the 1-N model is used. This means they are handled by a single CPU core instead of all cores:
>3.1.1 Handling different interrupt types in a multiprocessor system
>A GIC supports peripheral interrupts and software-generated interrupts, see Interrupt types on page 1-18.
>In a multiprocessor implementation the GIC handles:
>• software generated interrupts (SGIs) using the GIC N-N model
>• peripheral (hardware) interrupts using the GIC 1-N model.
To follow the spec, the model of all SPIs is set to 1-N in the constructor of the GIC. When SGIs are EOIed, the active and signaled state of the SPI has to be changed for all cores.

gic: distribute SPI 1-N

---

include/vcml/debugging/rspserver.h
src/vcml/debugging/gdbserver.cpp
src/vcml/debugging/rspserver.cpp

Also, return an error when a mem read fails.
Fixes: 457e7aa8880b4188f14171896001c4c47db25106 ("Be more lenient when gdb cannot read memory")

feat(rspserver): Use errnos as error codes
